import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { Footer } from "@/components/footer/footer";
import { AuthProvider } from "@/context/authContext";
import { ToastContainer } from "react-toastify";

// Configuración de fuentes
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Metadata de la página
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Layout de autenticación
export default function AuthLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <AuthProvider>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* Contenido dinámico */}
        {children}

        {/* Notificaciones */}
        <ToastContainer
          position="top-right"
          autoClose={3000}
          hideProgressBar={false}
          newestOnTop={false}
          closeOnClick
          pauseOnFocusLoss
          draggable
          pauseOnHover
          theme="dark"
        />

        {/* Footer */}
        <Footer />
      </body>
    </AuthProvider>
  );
}